[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Tom Hall", email = "thall-tom@hotmail.co.uk"},
]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

